### ISSUE TITLE
WPML compatibility

### ISSUE THREAD

**Issue by uhlhosting** [PayU-EMEA/plugin_woocommerce#23]
Hi,

Would be great to allow this plugin to work with WooCommerce Multilinngual from WPML. This plugin does not support at the  moment multi currency and wpml.

**Comment by uhlhosting** [comment]
```
2020-06-30T10:55:04+00:00 CRITICAL Uncaught Error: Call to a member function get() on null in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php:103
Stack trace:
#0 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#1 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#2 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#3 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#4 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
```

**Comment by uhlhosting** [comment]
Full stack trace:
`Stack trace:
#0 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#1 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#2 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#3 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#4 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#6 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#7 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#8 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#9 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#10 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#11 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#12 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#13 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#14 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#15 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#16 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#17 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#18 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#19 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#20 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#21 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#22 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#23 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#24 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#25 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#26 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#27 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#28 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#29 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#30 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#31 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#32 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#33 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#34 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#35 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#36 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#37 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#38 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#39 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#40 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#41 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#42 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#43 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#44 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#45 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#46 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#47 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#48 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#49 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#50 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#51 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#52 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#53 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#54 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#55 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#56 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#57 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#58 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#59 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#60 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#61 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#62 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#63 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#64 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#65 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#66 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#67 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#68 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#69 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#70 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#71 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#72 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#73 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#74 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#75 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#76 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#77 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#78 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#79 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#80 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#81 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#82 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#83 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#84 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#85 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#86 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#87 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#88 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#89 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#90 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#91 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#92 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#93 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#94 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#95 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#96 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#97 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#98 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#99 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#100 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#101 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#102 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#103 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#104 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#105 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#106 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#107 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#108 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#109 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#110 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#111 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#112 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#113 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#114 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#115 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#116 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#117 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#118 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#119 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#120 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#121 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#122 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#123 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#124 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#125 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#126 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#127 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#128 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#129 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#130 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#131 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#132 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#133 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#134 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#135 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#136 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#137 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#138 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#139 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#140 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#141 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#142 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#143 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
#144 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available()
#145 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways()
#146 /home/uhl/public_html/ecunative/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways()
#147 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('')
#148 /home/uhl/public_html/ecunative/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#149 /hom in /home/uhl/public_html/ecunative/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103`

**Comment by uhlhosting** [comment]
The fix would be this:

Hi again,

The issue is in the PayU plugin. The mentioned line from debug.log "103" should not run in the admin, but as the WC dashboard used the REST API it runs anyway.

To fix this we can share with you a workaround. Please replace on plugins\woo-payu-payment-gateway\includes\class-woocommerce-payu.php Line 93:


`if (!(is_admin())) {`

with 
`if (!(is_admin() || wp_is_json_request())) {`

**Comment by uhlhosting** [comment]
#1 So please inform us about the mentioned issue is caused by our workaround. Then we can check how many issues PayU causes before we contact the author.

#2 Please invite PayU into our Go-Global program so we can help them to certify PayU officially for use with WPML: https://wpml.org/documentation/theme-compatibility/go-global-program/
#3 For the currency, I see that this issue is already handled in another ticket: https://wpml.org/forums/topic/multi-currency-issues-on-orders-display-another-currency/


This above temporary fix is only for WooCommerce dashboard, REST APi is still broken, and also Health View.

**Comment by uhlhosting** [comment]
On WPML side issue can be tracked here: 

https://wpml.org/forums/topic/payu-have-some-incompatibility-with-woocommerce-multilingual-or-viceversa/page/5/#post-6523517

**Comment by uhlhosting** [comment]
```
The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.
 
The REST API call gave the following unexpected result: (500) 
Fatal error: Uncaught Error: Call to a member function get() on null in /home/ecunative/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php:103 Stack trace: #0 /home/ecunative/public_html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(151): WC_Gateway_PayU->is_available() #1 /home/ecunative/public_html/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(218): WC_Payment_Gateways->get_available_payment_gateways() #2 /home/ecunative/public_html/wp-content/plugins/woocommerce-multilingual/classes/multi-currency/payment-gateways/class-wcml-currencies-payment-gateways.php(93): WCML_Currencies_Payment_Gateways->get_available_payment_gateways() #3 /home/ecunative/public_html/wp-includes/class-wp-hook.php(287): WCML_Currencies_Payment_Gateways->init_gateways('') #4 /home/ecunative/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #5 /home/ecunative/public_html/ in /home/ecunative/public_html/wp-content/plugins/woo-payu-payment-gateway/includes/class-woocommerce-payu.php on line 103
 
There has been a critical error on your website.
```

It is very worrying that for several days no one bothered to reply to a certainly bothering and troubling issue with a payment gateway plugin. Is this github account dead?
